package com.example.dllo.project_a_cst.my_database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dllo.project_a_cst.my_database.MyMusicPerson;
import com.example.dllo.project_a_cst.my_database.MyPerson;

import com.example.dllo.project_a_cst.my_database.MyMusicPersonDao;
import com.example.dllo.project_a_cst.my_database.MyPersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myMusicPersonDaoConfig;
    private final DaoConfig myPersonDaoConfig;

    private final MyMusicPersonDao myMusicPersonDao;
    private final MyPersonDao myPersonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myMusicPersonDaoConfig = daoConfigMap.get(MyMusicPersonDao.class).clone();
        myMusicPersonDaoConfig.initIdentityScope(type);

        myPersonDaoConfig = daoConfigMap.get(MyPersonDao.class).clone();
        myPersonDaoConfig.initIdentityScope(type);

        myMusicPersonDao = new MyMusicPersonDao(myMusicPersonDaoConfig, this);
        myPersonDao = new MyPersonDao(myPersonDaoConfig, this);

        registerDao(MyMusicPerson.class, myMusicPersonDao);
        registerDao(MyPerson.class, myPersonDao);
    }
    
    public void clear() {
        myMusicPersonDaoConfig.clearIdentityScope();
        myPersonDaoConfig.clearIdentityScope();
    }

    public MyMusicPersonDao getMyMusicPersonDao() {
        return myMusicPersonDao;
    }

    public MyPersonDao getMyPersonDao() {
        return myPersonDao;
    }

}
